#!/bin/bash

#

# entregable

# Autor: Nicolás Rubio Cuéllar

# Fecha: 29-01-2024



clear



if [ $# -gt 2 ]; then

        echo "Número de parámetros incorrecto."

        exit

fi



if [ -f $1 ]; then

        echo "Este archivo ya existe."

        exit

fi



if [ ! -d $2 ]; then

        echo "Este directorio no existe."

        exit

fi



fichero=$(ls $2)

if [ -z $fichero ]; then

        echo "Este directorio está vacío"

        exit

fi



echo "Nicolás Rubio Cuéllar"



ficheros=$( ls $2/*.txt )



touch $1.txt



for i in $ficheros; do

        lineas=$( cat $i | wc -l )

        echo

        echo $i

        echo $lineas

        echo

        if [ $lineas -ge 5 ] && [ -f $1 ]; then

                cat $lineas

                echo $i >> $1.txt

        fi

done
